### ISSUE TITLE
Uncaught (in promise) Error: TypeError: Cannot set property 'links' of undefined

### ISSUE THREAD

**Issue by jesperlandberg** [Anthodpnt/Highway#1]
Hi (first woho).

Thanks for what seems like a nice little router. Will see how it fairs against ur colleagues Barba=)

I'm trying it on a wordpress site atm, and when using it with mode "both", i get this error when the transitions has finished:

**Uncaught (in promise) Error: TypeError: Cannot set property 'links' of undefined**

Any idea why? My markup and JS seems correct, have basically just copied ur examples to try it out.

Using out-in works fine tho!

Thanks!

**Comment by Anthodpnt** [comment]
Hi @jesperlandberg !

Thanks for trying Highway... 🤘🏼
This issue is **solved it the last release** ([v1.0.10](https://github.com/Anthodpnt/Highway/tree/v1.0.10)). 
The problem came from the context that was lost during the transition in `both` mode.

Note that since [v1.0.8](https://github.com/Anthodpnt/Highway/tree/v1.0.8) Highway is qualified as a **page loader** more than a **router** and for the sake of clarity the naming has been updated is the source code as well so don't forget to read the documentation and update your code if your version is older than the  [v1.0.8](https://github.com/Anthodpnt/Highway/tree/v1.0.8) 😉

I hope you'll like Highway as mush as Barba. It works like Barba but it's more flexible, modern and lightweight with as much features 😀

Best regards,
Anthodpnt
